<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Introduction to Medical Statistics with Jamovi - 8&nbsp; Inference for categorical data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./correlation.html" rel="next">
<link href="./more_samples.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><link href="site_libs/tabwid-1.1.2/tabwid.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for categorical data</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Medical Statistics with Jamovi</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/bougioukas/medstatsjamovi" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Medical Statistics</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability Distributions - Normal distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimation and Confidence Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for statistical inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two_samples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Inference for numerical data: 2 samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more_samples.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Inference for numerical data: &gt;2 samples</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./categorical.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for categorical data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simple linear regression</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Jamovi LAB</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab1.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">LAB I: Introduction to Jamovi</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab2.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">LAB II: Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab3.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">LAB III: Probability Distributions-Normal Distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab4.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">LAB IV: Estimation and Confidence Interval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab5.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">LAB V: Foundations for Statistical Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab6.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">LAB VI: Inference for numerical data (2 samples)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab7.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">LAB VII: Inference for numerical data (&gt;2 samples)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab8.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">LAB VIII: Inference for categorical data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab9.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">LAB IX: Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lab10.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">LAB X: Simple linear regression</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">8.1</span>  Introduction</a></li>
  <li>
<a href="#statistical-modeling-of-categorical-data" id="toc-statistical-modeling-of-categorical-data" class="nav-link" data-scroll-target="#statistical-modeling-of-categorical-data"><span class="toc-section-number">8.2</span>  Statistical modeling of categorical data</a>
  <ul class="collapse">
<li><a href="#estimating-p" id="toc-estimating-p" class="nav-link" data-scroll-target="#estimating-p">Estimating <span class="math inline">\(p\)</span></a></li>
  <li><a href="#tests-of-hypotheses-involving-p" id="toc-tests-of-hypotheses-involving-p" class="nav-link" data-scroll-target="#tests-of-hypotheses-involving-p">Tests of hypotheses involving <span class="math inline">\(p\)</span></a></li>
  </ul>
</li>
  <li>
<a href="#comparing-two-proportions-p_1-and-p_2" id="toc-comparing-two-proportions-p_1-and-p_2" class="nav-link" data-scroll-target="#comparing-two-proportions-p_1-and-p_2"><span class="toc-section-number">8.3</span>  Comparing two proportions <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span></a>
  <ul class="collapse">
<li><a href="#estimating-the-difference-p_1-p_2" id="toc-estimating-the-difference-p_1-p_2" class="nav-link" data-scroll-target="#estimating-the-difference-p_1-p_2">Estimating the difference <span class="math inline">\(p_1-p_2\)</span></a></li>
  </ul>
</li>
  <li>
<a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables"><span class="toc-section-number">8.4</span>  Contingency tables</a>
  <ul class="collapse">
<li><a href="#the-chi-square-test-of-association" id="toc-the-chi-square-test-of-association" class="nav-link" data-scroll-target="#the-chi-square-test-of-association">The chi-square test of association</a></li>
  </ul>
</li>
  <li>
<a href="#exposure-and-disease-the-concept-of-risk" id="toc-exposure-and-disease-the-concept-of-risk" class="nav-link" data-scroll-target="#exposure-and-disease-the-concept-of-risk"><span class="toc-section-number">8.5</span>  Exposure and disease: the concept of risk</a>
  <ul class="collapse">
<li><a href="#comparison-of-risks-the-risk-ratio" id="toc-comparison-of-risks-the-risk-ratio" class="nav-link" data-scroll-target="#comparison-of-risks-the-risk-ratio">Comparison of risks: the risk ratio</a></li>
  </ul>
</li>
  <li>
<a href="#the-odds-and-odds-ratio" id="toc-the-odds-and-odds-ratio" class="nav-link" data-scroll-target="#the-odds-and-odds-ratio"><span class="toc-section-number">8.6</span>  The odds and odds ratio</a>
  <ul class="collapse">
<li><a href="#case-control-studies" id="toc-case-control-studies" class="nav-link" data-scroll-target="#case-control-studies">Case-control studies</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-categorical" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for categorical data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><section id="introduction" class="level2" data-number="8.1"><h2 data-number="8.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">8.1</span> Introduction</h2>
<p>Different data types require different analytical approaches. In the previous chapters we discussed a number of ways to analyze and extract conclusions from continuous data [give some examples here]. Here we look at ways to perform analyses involving categorical data. “Categorical” are data where each observation implies membership to some group. For example, categorical data can be string of character values such as ‘M’ or ‘F’, dictating whether a person’s sex is male or female, or they can be numbers, such as 1, 2 or 3, symbolizing smoking status (where 1 might represent current smokers, 2, previous smokers and 3 people who never smoked). In medical research, categorical data frequently take on the form of membership in a response category (e.g., 1 for responders and 0 for non-responders), or exposure to some risk factor (e.g., 1 for exposed and 0 for not exposed), the occurrence of disease and so on.</p>
<p>When recording categorical data it is good practice to use numbers representing each category or group and then assigning a label to each number. The reason for this is that, unlike character values, numbers are, barring data entry error, virtually impossible to misspell. For this reason, all software packages include routines that assign labels to numbers which represent membership in some group. Here is an example, where we create a variable called <code>smoking</code>, which contains codes of the smoking status of 10 individuals:</p>
<p><strong>Coded data:</strong> 1, 2, 3, 3, 2, 1, 1, 2, 3, 3</p>
<p>where 1= Current, 2= Previous, and 3= Never.</p>
<div class="cell">

</div>
<p>(<strong>Labeled data:</strong> Current, Previous, Never, Never, Previous, Current, Current, Previous, Never, Never)</p>
<p>It is crucial to understand that, while using numbers to represent membership in some category, the numbers are <em>labels</em> and not actual numerical data. In other words, non-smokers do not have three times and previous smokers two times the value of current smokers! On the other hand, numbers are useful, both because of accuracy but also as labels of group membership when the data are <em>ordinal</em>. Ordinal are categorical data where there is an inherent ordering in the groups. In the example of smoking status, one may consider that previous smokers have lower exposure to smoking than current smokers and non-smokers even less exposure than previous smokers. So the sequence <span class="math inline">\(1 \rightarrow 2 \rightarrow 3\)</span> implies a decreasing cumulative exposure to smoking. This may have significant implications later on, if we want to assess the risk of a population in terms of experiencing cardiovascular disease for example, based on cumulative exposure to smoking. In fact, finding out that relationships follow some predictable ordering provides stronger evidence that the association of a categorical factor and some outcome is <em>causal</em>, that is the risk factor is the <em>cause</em> of the outcome and not related to the outcome in some random manner. For example, it is more definitive to establish that previous smokers have intermediate risk for lung cancer, between current smokers and non-smokers, than simply establishing that the risk in these three groups is different.</p>
</section><section id="statistical-modeling-of-categorical-data" class="level2" data-number="8.2"><h2 data-number="8.2" class="anchored" data-anchor-id="statistical-modeling-of-categorical-data">
<span class="header-section-number">8.2</span> Statistical modeling of categorical data</h2>
<p>The most common ways that categorical data are analyzed is through the binomial distribution. Recall from (<a href="distributions.html"><span>Chapter&nbsp;3</span></a>), the discussion about the binomial distribution. There we said that the probability that an outcome of interest occurs <span class="math inline">\(X=x\)</span> out of <span class="math inline">\(n\)</span> times is <span class="math display">\[
P(X=x)=\left (\begin{array}{c} n\\x\end{array}\right )p^x(1-p)^{n-x}
\]</span> where <span class="math inline">\(p\)</span> is the probability of observing a single such event. An example of this is modeling response to a medication. If <span class="math inline">\(n=20\)</span> people take this medication, the probability of observing <span class="math inline">\(X=8\)</span> with favorable response is, assuming the probability of each person responding is <span class="math inline">\(p=30\%\)</span> <span class="math display">\[
P(X=8)=\left (\begin{array}{c} 20\\8\end{array}\right )0.3^8(1-0.3)^{20-8}=0.114
\]</span> In other words, if we carry out a large number of similar clinical studies, we would expect to see 8/20 responders in only 11.4% of them. The reason is that, if the underlying response rate is <span class="math inline">\(p=0.3\)</span> we would expect to see, on average, <span class="math inline">\(np=20\times 0.3=6\)</span> responders. So, to see two more responders than expected on average has lower probability. Similarly, the probability that we would see <span class="math inline">\(x=10\)</span> responders is <span class="math inline">\(P(X=10)=0.031\)</span>, which is even lower than seeing <span class="math inline">\(x=8\)</span> responders. The same is true for the case where the number of responders is below the mean. For example, the probability of seeing <span class="math inline">\(x=2\)</span> responders is <span class="math inline">\(P(X=2)=0.028\)</span>. Plotting these probabilities we get the following trends:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-prob20patients" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-prob20patients-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Probability of response among 20 patients receiving a medication."><img src="categorical_files/figure-html/fig-prob20patients-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.1: Probability of response among 20 patients receiving a medication.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>So, as we get away from the mean (shown in purple in the figure) in either direction, the probability of observing either too large or too small a number of responders decreases.</p>
<section id="estimating-p" class="level3"><h3 class="anchored" data-anchor-id="estimating-p">Estimating <span class="math inline">\(p\)</span>
</h3>
<p>In many cases we do not know what <span class="math inline">\(p\)</span> is. For example, when we evaluate the response to a new drug, we do not know what the probability of a favorable response will be for someone taking the experimental medication. All we will be able to observe is the number of people with some given characteristic (e.g., a cancer diagnosis) who took the medication and the number among them that experienced a favorable response. In this case, we need to turn the problem on its head. Instead of asking what is the probability of seeing <span class="math inline">\(x\)</span> responders out of <span class="math inline">\(n\)</span> patients, if the response rate is <span class="math inline">\(p\)</span>, we ask what is the probability that <span class="math inline">\(p\)</span> is such and such, given that I have observed <span class="math inline">\(x\)</span> responders out of <span class="math inline">\(n\)</span> people who received the drug.</p>
<p>As we saw above, the probability of seeing a number of responders that is much higher or much lower than the average response <span class="math inline">\(np\)</span> is low. Conversely the probability that the <em>population response</em> is much higher or lower than the observed response in our study, i.e., <span class="math inline">\(\hat p=\frac{x}{n}=\frac{8}{20}=0.40\)</span>, will also be low. We can get an idea of these probabilities by performing a simulation. We will repeatedly generate virtual clinical trials like ours, with <span class="math inline">\(n=20\)</span> patients receiving a drug with and <span class="math inline">\(x=8\)</span> of them responding. In each of these simulations, I will consider response rates between 5% and 95% in increments of 5%. The proportion of time that <span class="math inline">\(x=8\)</span> responders were observed in the simulated trials when the population response rate is <span class="math inline">\(p=5\%, 10\%, 20\%, \cdots\)</span> will be the empirical probability distribution of <span class="math inline">\(p\)</span>. Here is this distribution:</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-empirical" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-empirical-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Empirical distribution of p from a study of x=8 responders among n=20 patients."><img src="categorical_files/figure-html/fig-empirical-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.2: Empirical distribution of <span class="math inline">\(p\)</span> from a study of <span class="math inline">\(x=8\)</span> responders among <span class="math inline">\(n=20\)</span> patients.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In the previous figure, we list the empirical (i.e., observed through simulation) distribution of <span class="math inline">\(p\)</span>, the population response inferred from <span class="math inline">\(x=8\)</span> responders out of <span class="math inline">\(n=20\)</span> study participants. The highest probability generated from these simulations corresponds to the observed proportion of responders <span class="math inline">\(\hat p=0.40\)</span>. Empirical probabilities diminish as one moves farther from <span class="math inline">\(\hat p\)</span> in either direction.</p>
<section id="the-normal-approximation-to-the-binomial-distribution" class="level4"><h4 class="anchored" data-anchor-id="the-normal-approximation-to-the-binomial-distribution">The normal approximation to the binomial distribution</h4>
<p>A simple (and, back when computers weren’t as powerful as they are today, necessary) approximation method of estimating <span class="math inline">\(p\)</span> is through the Central Limit Theorem. Without going too far into the weeds of the theory, the end result is that the quantity <span class="math display">\[
Z=\frac{\hat p-p}{\sqrt{p(1-p)/n}}\sim N(0,1)
\]</span> In other words, if we subtract from the observed response rate its (unknown) mean and divide it by its standard deviation, the resulting quantity will be distributed according to the normal distribution. Since <span class="math inline">\(p\)</span> is unknown, <span class="math inline">\(Z\)</span> can only be calculated if we make some assumption about the value of <span class="math inline">\(p\)</span>, the unknown population proportion. In the following figure, we consider several values for <span class="math inline">\(p\)</span> ranging from <span class="math inline">\(p=0.05,\cdots, 0.95\)</span>, so we can see what the distribution of <span class="math inline">\(p\)</span> based on the normal approximation to the binomial might look like. We also plot the distribution resulting from the previous simulation for comparison.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exactVSaprox" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-exactVSaprox-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Exact (red) distribution of the response rate p and distribution based on the normal approximation (green)."><img src="categorical_files/figure-html/fig-exactVSaprox-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.3: Exact (red) distribution of the response rate p and distribution based on the normal approximation (green).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The agreement between the exact and approximate results is very good. In general, if <span class="math inline">\(p\)</span> is not too small or too large, and <span class="math inline">\(n\)</span> the number of individuals under study is not too small, the normal approximation will be sufficient. A rule of thumb addressing both of these requirements is that the mean of the binomial distribution <span class="math inline">\(np&gt;5\)</span> and that <span class="math inline">\(n(1-p)&gt;5\)</span>. Thus, if <span class="math inline">\(p\)</span> is close to zero or one, the sample size must be higher to counteract the loss of precision in the normal approximation, but smaller sample sizes can be considered for values of <span class="math inline">\(p\)</span> away from the edges of the zero-one continuum.</p>
</section><section id="confidence-intervals-for-p" class="level4"><h4 class="anchored" data-anchor-id="confidence-intervals-for-p">Confidence intervals for <span class="math inline">\(p\)</span>
</h4>
<p>One very important use of the normal approximation is the construction of approximate confidence intervals for <span class="math inline">\(p\)</span>, something that is difficult to calculate exactly. As we saw previously in [put chapter reference here], a 95% two-sided confidence interval based on the normal distribution is bounded by <span class="math inline">\(\pm 2\)</span> standard deviations on either side of the mean. This is the case here as well, where the mean is the population mean and the standard deviation is <span class="math inline">\(\sigma=\sqrt{p(1-p)/n}\)</span>. So, an approximate 95% confidence interval for <span class="math inline">\(p\)</span> is <span class="math display">\[
\left (\hat p-1.96\times \sqrt{p(1-p)/n}), \hat p+1.96\times \sqrt{p(1-p)/n)}\right )
\]</span> where <span class="math inline">\(\hat p=\frac{x}{n}\)</span> is the observed proportion. As <span class="math inline">\(p\)</span> in the population is not known, the standard deviation is estimated by plugging in <span class="math inline">\(\hat p\)</span> for <span class="math inline">\(p\)</span> in the above equation. In the example above, <span class="math inline">\(\hat p=\frac{8}{20}=0.40\)</span> and thus, the 95% confidence interval is <span class="math display">\[\left ( 0.40-1.96\sqrt{(0.4)(0.6)/20}, 0.40+1.96\sqrt{(0.4)(0.6)/20}  \right )\]</span> <span class="math display">\[
\Downarrow
\]</span> <span class="math display">\[(0.185, 0.615)\]</span> The interpretation of this confidence interval is that, based on our observed <span class="math inline">\(x=8\)</span> responders out of <span class="math inline">\(n=20\)</span> individuals studied, we are 95% confident that the unknown true response rate is between <span class="math inline">\(p_l=18.5\%\)</span> and <span class="math inline">\(p_u=61.5\%\)</span>.</p>
</section></section><section id="tests-of-hypotheses-involving-p" class="level3"><h3 class="anchored" data-anchor-id="tests-of-hypotheses-involving-p">Tests of hypotheses involving <span class="math inline">\(p\)</span>
</h3>
<p>We can use the ideas presented in the last section to perform hypothesis testing involving <span class="math inline">\(p\)</span>. In medical statistics, such tests take on the form of assessing whether the observed data are consistent with an <em>a priori</em> hypothesis of what the response rate might be. This is very useful in clinical research for example, because we can use these methods to ascertain whether the data generated by a study are consistent with the response rate of a new drug exceeding some baseline level <span class="math inline">\(p_0\)</span>. Construction of such tests follows our usual process of forming a working or “null” hypothesis where the response rate of a new drug <span class="math inline">\(p\)</span> does <em>not</em> exceed <span class="math inline">\(p_0\)</span> and hope our data produce evidence to the contrary (what we call the <em>alternative</em> hypothesis). For example, if the historical response rate with current medications is 20%, our working or null hypothesis is to assume that the response rate <span class="math inline">\(p\)</span> of the experimental drug under study is no higher than baseline, i.e., <span class="math inline">\(H_0: p\leq p_0=0.20\)</span>. Then, using the data collected during the clinical trial, we can estimate <span class="math inline">\(p\)</span>, the response of the new drug, and see whether it is much higher than one would expect if the true response rate were <span class="math inline">\(p_0\)</span>.</p>
<p>As an example, let’s say that we undertake a clinical trial with <span class="math inline">\(n=20\)</span> participants and observe <span class="math inline">\(x=8\)</span> responses. One way to decide whether <span class="math inline">\(p\leq p_0\)</span> can be based on the lower bound of a 95% one-sided confidence interval for <span class="math inline">\(p\)</span> generated by the observed data. We will discuss how this interval is constructed in a second. To see why this is a viable approach, recall that confidence intervals contain all the plausible scenarios about the response rate (for the given confidence level of course). Thus, if the lower bound of these plausible values is higher than <span class="math inline">\(p_0\)</span>, then all values of <span class="math inline">\(p\)</span> one can envision are higher than <span class="math inline">\(p_0\)</span> as well. If our desired confidence level were, say, 95% and we observed this, we would be 95% “confident” that the response rate is <span class="math inline">\(p&gt;p_0\)</span>. In that case we would conclude that the new drug improves upon the current baseline response rate.</p>
<p>To construct such a confidence interval we can use either the exact binomial distribution or the normal approximation. In the first case, the lower bound of the one-sided 95% confidence interval for <span class="math inline">\(p\)</span>, the response rate of the experimental drug, based on observed data of <span class="math inline">\(x=8\)</span> responses out of <span class="math inline">\(n=20\)</span> study participants,</p>
<p>An alternative way to go about this is by using the normal approximation to the binomial. We saw in [cite chapter here] that the lower bound of a one-sided 95% confidence interval, based on the normal distribution, is 1.645 standard deviations below the mean. If the mean in our case is estimated by <span class="math inline">\(\hat p=\frac{8}{20}=0.40\)</span>, and the standar deviation by <span class="math inline">\(s=\sqrt{\hat p(1-\hat p)/n}=0.11\)</span>, then the lower bound of the one-sided 95% confidence interval is <span class="math inline">\(p_l=0.22\)</span>. This very close to the exact bound shown above.</p>
<p>The conclusion from both types of confidence intervals is that the smallest value for the response rate of the experimental drug that anyone could envision with 95% confidence is around <span class="math inline">\(22\%-23\%\)</span>. This is higher than the baseline rate <span class="math inline">\(p_0=20\%\)</span>. In turn, this means that, based on the observed number of <span class="math inline">\(x=8\)</span> responses in our study out of <span class="math inline">\(n=20\)</span> participants, the unknown population response rate for the drug under study is higher than <span class="math inline">\(p_0=20\%\)</span>.</p>
</section></section><section id="comparing-two-proportions-p_1-and-p_2" class="level2" data-number="8.3"><h2 data-number="8.3" class="anchored" data-anchor-id="comparing-two-proportions-p_1-and-p_2">
<span class="header-section-number">8.3</span> Comparing two proportions <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>
</h2>
<p>Comparing a proportion, like the rate of response to a medication, to a historical or external baseline rate is an efficient way to estimate it without involving large samples. However, the level of evidence obtained from such an analysis is not as high as comparing two populations head to head. In clinical research for example, data at the source of the baseline estimate of the response rate were not collected under circumstances which are identical to our current study, they were collected in different time periods, on different populations and so on. The more definitive approach is to compare two concurrently sampled populations, one taking the current standard therapy and one receiving the experimental therapy. The same is true when we assess the risk of disease based on some exposure. We can compare the observed frequency of the occurrence of the disease to a historical rate. However, more definitive conclusions can be obtained when we compare some exposure between two populations and compare the frequency of occurrence of some outcome between them (e.g., occurrence of melanoma to populations at different exposure levels to sunlight).</p>
<section id="estimating-the-difference-p_1-p_2" class="level3"><h3 class="anchored" data-anchor-id="estimating-the-difference-p_1-p_2">Estimating the difference <span class="math inline">\(p_1-p_2\)</span>
</h3>
<p>The ability to estimate the difference of two proportions is important for a number of reasons. It provides an idea of whether <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> are equal. In clinical investigation, this addresses the question whether the response to a new drug is higher compared to the standard of care. In epidemiology, these proportions may reflect whether the risk of occurrence of some disease is different among individuals who were or were not exposed to some risk factor.</p>
<p>As the true proportions in the populations under study are not known, we will need to estimate them from sampled data. The usual strategy can be applied, where we sample <span class="math inline">\(n_1\)</span> people in the first group (people receiving a specific medication or being exposed to some factor) and <span class="math inline">\(n_2\)</span> in the second group and count the number of times <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, that the characteristic of interest (response to a medication or presence of disease) has occurred in each group respectively. From these two samples we can obtain our best (“point”) estimates for <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> as <span class="math inline">\(\hat p_1=\frac{x_1}{n_1}\)</span> and <span class="math inline">\(\hat p_2=\frac{x_2}{n_2}\)</span>. Consequently, our best estimate for the difference <span class="math inline">\(p_1-p_2\)</span> will be <span class="math inline">\(\hat p_1-\hat p_2\)</span>. None of this is too complicated. Where matters start getting interesting is when we want to estimate the distribution of the difference of the two proportions. Deriving a distribution is a crucial task because it gives us an idea of what differences are more likely to occur and which are less likely. In its more immediate use, obtaining this distribution allows us to construct confidence intervals for the difference in the two proportions. It can also help us construct a criterion based on which we will decide whether the two proportions are equal or not.</p>
<section id="the-normal-approximation-to-the-distribution-of-hat-p_1-hat-p_2" class="level4"><h4 class="anchored" data-anchor-id="the-normal-approximation-to-the-distribution-of-hat-p_1-hat-p_2">The normal approximation to the distribution of <span class="math inline">\(\hat p_1-\hat p_2\)</span>
</h4>
<p>The simplest way to estimate the distribution of the difference of two proportions is by using the normal approximation to the binomial distribution. Statistical theory, which we will not go into here, prescribes that, assuming that <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are not too small and <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> too small or two large, the distribution of <span class="math inline">\(\hat p_1-\hat p_2\)</span> is close to a normal distribution with mean <span class="math inline">\(p_1-p_2\)</span> and standard deviation <span class="math inline">\(\sqrt{\frac{p_1(1-p_1)}{n_1}+\frac{p_2(1-p_2)}{n_2}}\)</span>.</p>
<p>For example, consider the trial of belotecan versus topotecan in recurrent ovarian cancer (<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7853132/">Kim et al., <em>Br J Cancer</em>, 2021</a>). In that study, <span class="math inline">\(n_1=71\)</span> women diagnosed with recurrent ovarian cancer received belotecan 0.5 mg/m<sup>2</sup> and <span class="math inline">\(n_2=69\)</span> topotecan 1.5 mg/m<sup>2</sup> for five consecutive days every 3 weeks. The study based its conclusion on the difference in overall response rate between the two treatment groups. At the completion of the study, <span class="math inline">\(x_1=21\)</span> subjects in the belotecan arm had a partial or complete response (so <span class="math inline">\(\hat p_1=29.6\%\)</span>), compared to <span class="math inline">\(x_2=18\)</span> in the topotecan arm (<span class="math inline">\(\hat p_1=26.1\%\)</span>). The normal approximation to the distribution of the difference is shown in the next figure.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ovarian" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-ovarian-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Normal approximation to the distribution of the difference in overall response rates in the ovarian cancer study plus observed overall response rate difference in the two treatment arms (dashed line)."><img src="categorical_files/figure-html/fig-ovarian-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.4: Normal approximation to the distribution of the difference in overall response rates in the ovarian cancer study plus observed overall response rate difference in the two treatment arms (dashed line).</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="confidence-intervals-for-p_1-p_2" class="level4"><h4 class="anchored" data-anchor-id="confidence-intervals-for-p_1-p_2">Confidence intervals for <span class="math inline">\(p_1-p_2\)</span>
</h4>
<p>Confidence intervals for the difference of two proportions can be calculated as usual by appealing to properties of the normal distribution. For example, a 95% two-sided confidence interval in the previous example will be <span class="math display">\[
\small
\left ( \hat p_1-\hat p_2-1.96\times \sqrt{\frac{p_1(1-p_1)}{n_1}+\frac{p_2(1-p_2)}{n-2}},
\hat p_1-\hat p_2+1.96\times \sqrt{\frac{p_1(1-p_1)}{n_1}+\frac{p_2(1-p_2)}{n-2}}\right )
\]</span> In the above, <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> are not known, so we substitute <span class="math inline">\(\hat p_1\)</span> and <span class="math inline">\(\hat p_2\)</span> for them respectively in order to calculate the confidence interval. Theory tells us that this will work if <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> are not too small. In the ovarian cancer study example, the 95% two-sided confidence interval of the difference in overall response rates between belotecan and topotecan is <span class="math display">\[
(-0.113,
0.183)
\]</span> The interpretation of the above confidence interval is that we expect that 95% of the time, the unknown difference in the two response rates will be between <span class="math inline">\(11.3\%\)</span> in favor of topotecan (implying that the topotecan response rate is larger than belotecan’s) and <span class="math inline">\(18.3\%\)</span> in favor of belotecan (implying that the response rate of belotecan is larger than topotecan’s).</p>
</section><section id="testing-hypotheses-involving-p_1-and-p_2" class="level4"><h4 class="anchored" data-anchor-id="testing-hypotheses-involving-p_1-and-p_2">Testing hypotheses involving <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>
</h4>
<p>Following our usual strategy for performing tests of statistical hypotheses, our working or null hypothesis is that there is no difference between the response rates corresponding to the two groups, i.e., <span class="math inline">\(H_0: p_1=p_2\)</span> or, equivalently, <span class="math inline">\(H_0:p_1-p_2=0\)</span>. An immediate way to decide whether the null hypothesis is true is through the confidence interval of <span class="math inline">\(p_1-p_2\)</span> constructed in the previous section. Recall that confidence intervals include all the plausible values which are anticipated based on some pre-specified confidence level. So, one way to check whether the null hypothesis is correct, is by looking to see whether the value of the difference under the null hypothesis is contained within the confidence interval. If the answer is “yes”, then the evidence from the data is consistent with the null hypothesis, so we do not reject <span class="math inline">\(H_0\)</span>. Conversely, if this value is not included in the confidence interval, then it is not among the plausible values implied by our working hypothesis, so we reject it. Here note that the difference between <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> does not have to be zero under <span class="math inline">\(H_0\)</span>. In a number of situations (most notable among them are non-inferiority study designs), the difference may be some nonzero number. All of the methods discussed here can also be applied in those cases as well.</p>
<p>Working through this logic in the previous example, we see that <span class="math inline">\(p_1-p_2=0\)</span> is included in the 95% two-sided confidence interval, since its bounds straddle zero. This is evidence consistent with the hypothesis that there is no difference in the overall response rate between the two drugs. A pictorial representation of what we just said follows.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ovarian2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-ovarian2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Two-sided 95% confidence interval of the difference in overall response rates in the ovarian cancer study versus its value under H_0 (dashed line)."><img src="categorical_files/figure-html/fig-ovarian2-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.5: Two-sided 95% confidence interval of the difference in overall response rates in the ovarian cancer study versus its value under <span class="math inline">\(H_0\)</span> (dashed line).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We can also carry out this test based on a single p value associated with the following statistic <span class="math display">\[
Z=\frac{\hat p_1-\hat p_2}{\sqrt{\hat p(1-\hat p) \left ( \frac{1}{n_1}+\frac{1}{n_2}\right )}}\sim N(0,1)
\]</span> where <span class="math inline">\(\hat p=\frac{x_1+x_2}{n_1+n_2}\)</span> is a <em>pooled</em> estimate of the common response rate <span class="math inline">\(p\)</span>. Note that, if <span class="math inline">\(p_1=p_2\)</span>, as it is assumed under the null hypothesis, the observed response rates in the two groups are simply random manifestations of the true single population response rate. So our best estimate is to use the entire data set to estimate the common rate. We do so by obtaining the single response rate resulting from pooling the observed responses <span class="math inline">\(x_1+x_2\)</span>and dividing this sum by the total sample size <span class="math inline">\(n_1+n_2\)</span> in the two groups.</p>
<p>The p value is calculated as the probability of seeing the observed <span class="math inline">\(Z\)</span> value or any other value that is more extreme (i.e., to the right of a <span class="math inline">\(Z\)</span> and/or to the left of a negative <span class="math inline">\(Z\)</span> value) if our working hypothesis is true. If this probability is low (i.e., below our <em>a priori</em> specified alpha level) then we reject the null hypothesis, as low p values suggest that the evidence provided by the observed data are not consistent with the working hypothesis. In this case, we reject <span class="math inline">\(H_0:p_1=p_2\)</span> and conclude that <span class="math inline">\(p_1\neq p_2\)</span>. Conversely, if the p value is high, then the probability that we see a difference like the one observed in this study is high, so the evidence produced by the data is consistent with the null hypothesis. In this case we do <em>not</em> reject the null hypothesis. The “and/or” in the definition of the p value above comes into play when the null hypothesis is two-sided. In this case, <em>both</em> the areas under the curve to the right of <span class="math inline">\(|Z|\)</span> and the left of <span class="math inline">\(-|Z|\)</span> are summed up. In the ovarian cancer example, our null hypothesis is two-sided (i.e., it does not imply direction of the superiority or inferiority in the difference) so the p value is calculated as shown in the colored areas of the next figure.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ovarian3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-ovarian3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Calculation of a p-value associated with the difference in overall response rates in the ovarian cancer study. Both the areas under the curve of the shaded regions are summed to produce the two-sided p value."><img src="categorical_files/figure-html/fig-ovarian3-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.6: Calculation of a p-value associated with the difference in overall response rates in the ovarian cancer study. Both the areas under the curve of the shaded regions are summed to produce the two-sided p value.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In the above figure, summing up the two shaded regions to the right of <span class="math inline">\(Z\)</span> and to the left of <span class="math inline">\(-Z\)</span> gives us a p value <span class="math inline">\(p=0.645\)</span>. Since the p value is not below <span class="math inline">\(\alpha=0.05\)</span>, the data are consistent with the working hypothesis of no difference between the response rates in the belotecan and topotecan arms. We conclude that there is no evidence that the overall response rates are different in the two drugs.</p>
</section></section></section><section id="contingency-tables" class="level2" data-number="8.4"><h2 data-number="8.4" class="anchored" data-anchor-id="contingency-tables">
<span class="header-section-number">8.4</span> Contingency tables</h2>
<p>A very useful way of presenting data that express the frequency of the occurrence of some event, is through cross-tabulations. For example, response to treatment, among women participating in the ovarian cancer clinical trial described in the previous section, can be presented as a <span class="math inline">\(2\times 2\)</span> cross-tabulation of those who received belotecan or topotecan versus those who experienced a partial or complete response of their tumors and those who did not.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ct1" class="anchored">

<div class="tabwid">
<style>.cl-2483e65c{}.cl-247b7242{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-247ed4c8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-247ed4c9{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-247ee990{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-247ee99a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-247ee99b{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-247ee9a4{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-247ee9a5{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-247ee9a6{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table class="cl-2483e65c">
<caption>Table&nbsp;8.1:  Response frequency by treatment arm in the reccurrent ovarian cancer study. </caption>
<thead>
<tr style="overflow-wrap:break-word;">
<th class="cl-247ee990"><p class="cl-247ed4c8"><span class="cl-247b7242"></span></p></th>
<th colspan="2" class="cl-247ee99a"><p class="cl-247ed4c9"><span class="cl-247b7242">Treatment group</span></p></th>
<th class="cl-247ee99a"><p class="cl-247ed4c9"><span class="cl-247b7242"></span></p></th>
</tr>
<tr style="overflow-wrap:break-word;">
<th class="cl-247ee990"><p class="cl-247ed4c8"><span class="cl-247b7242">Response</span></p></th>
<th class="cl-247ee99a"><p class="cl-247ed4c9"><span class="cl-247b7242">Belotecan </span></p></th>
<th class="cl-247ee99a"><p class="cl-247ed4c9"><span class="cl-247b7242">Topotecan</span></p></th>
<th class="cl-247ee99a"><p class="cl-247ed4c9"><span class="cl-247b7242">Total</span></p></th>
</tr>
</thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-247ee99b"><p class="cl-247ed4c8"><span class="cl-247b7242">Yes</span></p></td>
<td class="cl-247ee9a4"><p class="cl-247ed4c9"><span class="cl-247b7242">21</span></p></td>
<td class="cl-247ee9a4"><p class="cl-247ed4c9"><span class="cl-247b7242">18</span></p></td>
<td class="cl-247ee9a4"><p class="cl-247ed4c9"><span class="cl-247b7242">39</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-247ee99b"><p class="cl-247ed4c8"><span class="cl-247b7242">No</span></p></td>
<td class="cl-247ee9a4"><p class="cl-247ed4c9"><span class="cl-247b7242">50</span></p></td>
<td class="cl-247ee9a4"><p class="cl-247ed4c9"><span class="cl-247b7242">51</span></p></td>
<td class="cl-247ee9a4"><p class="cl-247ed4c9"><span class="cl-247b7242">101</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-247ee9a5"><p class="cl-247ed4c8"><span class="cl-247b7242">Total</span></p></td>
<td class="cl-247ee9a6"><p class="cl-247ed4c9"><span class="cl-247b7242">71</span></p></td>
<td class="cl-247ee9a6"><p class="cl-247ed4c9"><span class="cl-247b7242">69</span></p></td>
<td class="cl-247ee9a6"><p class="cl-247ed4c9"><span class="cl-247b7242">140</span></p></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>Contingency tables are also used when we summarize data which are related to the occurrence of disease separated by whether an individual had been exposed to some risk factor or not. Here is an example of data from the <a href="https://academic.oup.com/ije/article/41/2/359/690712">Electricity Generating Authority of Thailand (EGAT) cohort</a> (Vathesatogkit et al., <em>Int J Epi</em>, 2012). This study (also see <em>Epidemiology: Study Design and Data Analysis, Third Edition</em> by Mark Woodward, Chapman &amp; Hall/CRC Texts in Statistical Science, 2014, page 91) followed a cohort of employees of the Electricity Generating Authority of Thailand. Study participants filled out a questionnaire at entry into the study where, among other information, they were asked about whether they smoked. Twelve years later, data on deaths from cardiovascular disease (CVD) were available on 3,315 individuals (over 95% of the original study cohort). Here is a summary of these data.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-ct2" class="anchored">

<div class="tabwid">
<style>.cl-24a41184{table-layout:auto;}.cl-249c483c{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-249f4e92{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-249f4e93{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-249f617a{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-249f617b{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-249f6184{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-249f6185{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-249f6186{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-249f618e{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table class="cl-24a41184">
<caption>Table&nbsp;8.2:  CVD by smoking status in the EGAT study. </caption>
<thead>
<tr style="overflow-wrap:break-word;">
<th class="cl-249f617a"><p class="cl-249f4e92"><span class="cl-249c483c"></span></p></th>
<th colspan="2" class="cl-249f617b"><p class="cl-249f4e93"><span class="cl-249c483c">Smoker?</span></p></th>
<th class="cl-249f617b"><p class="cl-249f4e93"><span class="cl-249c483c"></span></p></th>
</tr>
<tr style="overflow-wrap:break-word;">
<th class="cl-249f617a"><p class="cl-249f4e92"><span class="cl-249c483c">Death from CVD?</span></p></th>
<th class="cl-249f617b"><p class="cl-249f4e93"><span class="cl-249c483c">Yes </span></p></th>
<th class="cl-249f617b"><p class="cl-249f4e93"><span class="cl-249c483c">No</span></p></th>
<th class="cl-249f617b"><p class="cl-249f4e93"><span class="cl-249c483c">Total</span></p></th>
</tr>
</thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-249f6184"><p class="cl-249f4e92"><span class="cl-249c483c">Yes</span></p></td>
<td class="cl-249f6185"><p class="cl-249f4e93"><span class="cl-249c483c">31</span></p></td>
<td class="cl-249f6185"><p class="cl-249f4e93"><span class="cl-249c483c">15</span></p></td>
<td class="cl-249f6185"><p class="cl-249f4e93"><span class="cl-249c483c">46</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-249f6184"><p class="cl-249f4e92"><span class="cl-249c483c">No</span></p></td>
<td class="cl-249f6185"><p class="cl-249f4e93"><span class="cl-249c483c">1,386</span></p></td>
<td class="cl-249f6185"><p class="cl-249f4e93"><span class="cl-249c483c">1,883</span></p></td>
<td class="cl-249f6185"><p class="cl-249f4e93"><span class="cl-249c483c">3,269</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-249f6186"><p class="cl-249f4e92"><span class="cl-249c483c">Total</span></p></td>
<td class="cl-249f618e"><p class="cl-249f4e93"><span class="cl-249c483c">1,417</span></p></td>
<td class="cl-249f618e"><p class="cl-249f4e93"><span class="cl-249c483c">1,898</span></p></td>
<td class="cl-249f618e"><p class="cl-249f4e93"><span class="cl-249c483c">3,315</span></p></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>In both of the above examples, the scientific question is about whether exposure to a certain medication (belotecan or topotecan in the ovarian cancer trial) or a risk factor (smoking in the EGAT cohort study) is <em>associated</em> with the probability that a person will experience a certain event. In the case of the clinical trial, the event of interest is overall response to treatment. In the EGAT observational cohort study it is the risk of dying with evidence of cardiovascular disease. While the interpretation of the two outcomes is different (probability of response to treatment versus risk of disease occurrence), conclusions on the potential association of exposure with the outcome is based on the proportion of individuals who experienced the event of interest (response or death from CVD) out of all persons under study. Consequently, the same methods can be applied to address both of these questions.</p>
<section id="the-chi-square-test-of-association" class="level3"><h3 class="anchored" data-anchor-id="the-chi-square-test-of-association">The chi-square test of association</h3>
<p>Let’s go back to the ovarian cancer study. The investigators were keen on finding out whether response rates to belotecan were different from those of topotecan. We discussed previously how this question might be answered by comparing the response rates in the two treatment arms. Another way, which will turn out to produce equivalent results, is to address whether taking a specific medication is <em>associated</em> to the overall rate of response. Seen from the perspective of an individual patient, this is the probability that they respond to medication. How might this associational question be answered? Well let’s see what are the implications of a working hypothesis of no association. Consider the table from the ovarian cancer data, with the internal counts removed:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ct3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-ct3-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="TEXT TEXT."><img src="categorical_files/figure-html/fig-ct3-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.7: TEXT TEXT.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>As we discussed earlier, in the absence of any association between drug exposure and response, the best estimate of the probability of response is <span class="math inline">\(\hat p=\frac{x_1+x_2}{n_1+n_2}=\frac{21+18}{71+69}=0.279\)</span>. Given properties of proportions described in chapter [cite chapter here], when discussing the binomial distribution, we would expect that, on average, <span class="math inline">\(n_1\hat p=19.8\)</span> individuals will respond in the belotecan arm and <span class="math inline">\(n_2\hat p=19.2\)</span> subjects will respond in the topotecan arm. Conversely, <span class="math inline">\(n_1(1-\hat p)=51.2\)</span> and <span class="math inline">\(n_2(1-\hat p)=49.8\)</span> study participants will be expected to <em>not</em> respond in the two arms respectively. Consequently, under the assumption of no association between treatment and response, Table 1 above should have looked like this:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ct4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-ct4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="TEXT TEXT."><img src="categorical_files/figure-html/fig-ct4-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.8: TEXT TEXT.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>So slightly <em>less</em> people would be expected to have responded in the belotecan arm, 19.8 versus 21, and slightly <em>more</em> people would be expected to have responded in the topotecan arm, 19.2 versus 18, if there were no association between which treatment was taken and response to the drug. In addition, slightly more people, 51.2 versus 50 would be expected not to respond in the belotecan arm and slightly less, 49.8 versus 51, in the topotecan arm.</p>
<p>The question which will help us reach a conclusion is whether the observed average counts are too different from what would be expected, if there were no association between treatment and response, beyond what would be attributable to chance alone. To test this formally, we use a statistic which aggregates the squared differences between the counts that would be expected and those that are actually observed as proportions of the expected counts. This is, <span class="math display">\[
X=\sum_{i=1}^{r\times c}\frac{(O_i-E_i)^2}{E_i}
\]</span> where <span class="math inline">\(O_i\)</span> and <span class="math inline">\(E_i\)</span> are, respectively, the observed and expected counts in each of the <span class="math inline">\(r\times c\)</span> interior cells of the contingency table. In our example, the number of rows and columns in the table, <span class="math inline">\(r=2\)</span> and <span class="math inline">\(c=2\)</span>, but this is not always the case. This methodology will work for other combinations of <span class="math inline">\(r\)</span> and <span class="math inline">\(c\)</span> as well. Taking the squared differences underlines our lack of preference about whether the deviation from what is expected from the null hypothesis is in one direction or the other, so squared differences are useful as they correspond to our understanding of the problem.</p>
<p>However, most importantly, the sum of the squared differences between observed counts and expected counts, has a known distribution. The distribution of the statistic, generated by aggregating the square differences of observed and expected counts is the chi-square distribution, indexed by degrees of freedom which are equal to <span class="math inline">\((c-1)\times (r-1)\)</span>. Having a known distribution is important, because we can quantify how likely it is to observe the test statistic that is generated by adding together these square counts if there is no association between the two factors in the table (here treatment and response). If the observed statistic is unlikely to have occurred, we will reject the null hypothesis in favor of the alternative that there is a significant association between the factors under consideration. We can also generate p values using this statistic. These correspond to the area under the chi-square curve to the right of the observed statistic.</p>
<p>Let’s implement the chi-square test in the ovarian cancer example. The chi-square statistic is <span class="math display">\[X=\frac{(21 -19.8)^2}{19.8}+ \frac{(18-19.2)^2}{19.2} + \frac{(50-51.2)^2}{51.2} + \frac{(51 -49.8)^2}{49.8}= 0.212\]</span> The p value associated with this test statistic, compared to a chi-square distribution with <span class="math inline">\(1=(2-1)\times (2-1)\)</span> degrees of freedom, is <span class="math inline">\(p=0.645\)</span>. The pictorial representation of this test is shown in the following figure.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-chi_distribution" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-chi_distribution-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="The chi-square distribution and observed test statistic in the ovarian cancer trial."><img src="categorical_files/figure-html/fig-chi_distribution-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.9: The chi-square distribution and observed test statistic in the ovarian cancer trial.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The conclusion from this analysis is that there does not appear to be sufficient evidence in these data supporting an association between taking belotecan or topotecan and responding to the medication or not.</p>
<p>These results are consistent with our earlier conclusion that there is no difference between the response rates in the two treatment arms. As it turns out, the two tests are <em>equivalent</em>! Recall that our test statistic in the comparison of <span class="math inline">\(p_1\)</span> versus <span class="math inline">\(p_2\)</span>, the response rates in the ovarian cancer study, was <span class="math inline">\(Z=0.461\)</span>. This is equal to <span class="math inline">\(\sqrt{X}=\sqrt{0.212}=0.461\)</span>). That is, the <span class="math inline">\(Z\)</span> statistic in the test of the difference between two proportions is equal to the square root of the chi-square statistic from the <span class="math inline">\(2\times 2\)</span> table testing the association between two factors. So, in the special case of <span class="math inline">\(2\times 2\)</span> contingency tables, the <span class="math inline">\(Z\)</span> test of difference between <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> and the chi-square test of the association of two factors are equivalent as they address the same question from two different perspectives. This relationship is not generally true for chi-square tests involving arbitrary <span class="math inline">\(r\times c\)</span> contingency tables.</p>
</section></section><section id="exposure-and-disease-the-concept-of-risk" class="level2" data-number="8.5"><h2 data-number="8.5" class="anchored" data-anchor-id="exposure-and-disease-the-concept-of-risk">
<span class="header-section-number">8.5</span> Exposure and disease: the concept of risk</h2>
<p>In epidemiology, a major concept that people study is that of risk. Risk is the probability that one would observe some (usually adverse) event. We talk about the risk of heart disease, or the risk of cancer for example. Risk can also be the probability of experiencing a positive event such as disease remission or response to a medication. This latter interpretation applies to the idea of risk as a proportion or probability rather than the negative meaning of the everyday use of the word.</p>
<div class="cell">

</div>
<p>In the EGAT cohort study, the investigators assessed the risk of cardiovascular disease (CVD). In the <span class="math inline">\(2\times 2\)</span> table summarizing the frequency of CVD-related deaths and smoking status, the risk of CVD among the smokers is defined as the frequency of persons dying with evidence of CVD out of all smokers. Similarly, the risk of CVD among the non-smokers is the proportion of CVD-related deaths among people who were not smoking at the start of the study. This means that the risk of CVD among smokers is <span class="math inline">\(r_1=0.0219\)</span> and the same among non-smokers is <span class="math inline">\(r_2=0.0079\)</span>. The pictorial representation of this is as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-egat" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><a href="categorical_files/figure-html/fig-egat-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Percent of CVD deaths among smokers and non-smokers in the EGAT cohort study."><img src="categorical_files/figure-html/fig-egat-1.png" class="img-fluid figure-img" width="672"></a></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.10: Percent of CVD deaths among smokers and non-smokers in the EGAT cohort study.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>At first glance, it appears that the risk of CVD among smokers is almost three-fold higher compared to non-smokers. However, is an absolute difference of 1.4% sufficient for us to conclude that smoking is associated with a higher CVD risk?</p>
<p>To understand whether smoking predisposes someone to a higher risk for CVD death, researchers may compare the risk between smokers and non-smokers (the <em>exposure</em> factor). Of course we can address this question by testing for a possible <em>association</em> between smoking and CVD. The chi-square test for this association is as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-chi_test" class="anchored">

<div class="tabwid">
<style>.cl-26a95c1e{table-layout:auto;}.cl-26a17e68{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-26a49d1e{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-26a49d28{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-26a4af3e{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26a4af48{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26a4af52{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26a4af53{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table class="cl-26a95c1e">
<caption>Table&nbsp;8.3:  Chi-square test of the association between CVD and smoking status in the EGAT study. </caption>
<thead><tr style="overflow-wrap:break-word;">
<th class="cl-26a4af3e"><p class="cl-26a49d1e"><span class="cl-26a17e68">Test statistic</span></p></th>
<th class="cl-26a4af48"><p class="cl-26a49d28"><span class="cl-26a17e68">Obs. value</span></p></th>
<th class="cl-26a4af48"><p class="cl-26a49d28"><span class="cl-26a17e68">DF</span></p></th>
<th class="cl-26a4af48"><p class="cl-26a49d28"><span class="cl-26a17e68">P value</span></p></th>
<th class="cl-26a4af3e"><p class="cl-26a49d1e"><span class="cl-26a17e68"></span></p></th>
<th class="cl-26a4af48"><p class="cl-26a49d28"><span class="cl-26a17e68">N</span></p></th>
</tr></thead>
<tbody><tr style="overflow-wrap:break-word;">
<td class="cl-26a4af52"><p class="cl-26a49d1e"><span class="cl-26a17e68">χ²</span></p></td>
<td class="cl-26a4af53"><p class="cl-26a49d28"><span class="cl-26a17e68">11.57784</span></p></td>
<td class="cl-26a4af53"><p class="cl-26a49d28"><span class="cl-26a17e68">1</span></p></td>
<td class="cl-26a4af53"><p class="cl-26a49d28"><span class="cl-26a17e68">0.0006674236</span></p></td>
<td class="cl-26a4af52"><p class="cl-26a49d1e"><span class="cl-26a17e68">N</span></p></td>
<td class="cl-26a4af53"><p class="cl-26a49d28"><span class="cl-26a17e68">3,315</span></p></td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
<p>We see here that the observed chi-square statistic in the EGAT study is <span class="math inline">\(X=11.6\)</span> with an associated p value <span class="math inline">\(p=0.000667&lt;0.05=\alpha\)</span>. So we conclude that the evidence from the data is not consistent with the null hypothesis of no association between smoking and CVD. There appears to be strong evidence of an association between smoking death from cardiovascular disease.</p>
<section id="comparison-of-risks-the-risk-ratio" class="level3"><h3 class="anchored" data-anchor-id="comparison-of-risks-the-risk-ratio">Comparison of risks: the risk ratio</h3>
<p>The previous analysis is addressing the question of association but does not provide direct information about the actual levels of risk and, more importantly, the difference in risk between the two exposure groups (i.e., smokers and non-smokers). We addressed this question with chi-square test of association in the previous chapter. This, as we discussed earlier, is equivalent with the test of the difference between two proportions. So the chi-square test addresses the question of whether the levels of CVD risks are the same among smokers and non-smokers. Another way to address the same question is to estimate the risk <em>ratio</em>. This is the ratio of the risk in the exposed group (smokers here) over the risk in the unexposed group (non-smokers). In the EGAT study, the risk ratio is <span class="math display">\[
RR=\frac{\frac{31}{1417}}{\frac{15}{1898}}=2.77\]</span></p>
<p>In other words, the relative risk of CVD is almost three-fold higher compared to non-smokers. To see whether this apparent enormous increase in risk is statistically significant (i.e., it is larger than what would be expected by chance), we have to test this formally. To do so, we need to recast the null hypothesis that CVD risk is not <em>different</em> between smokers and non-smokers in terms of a <em>ratio</em> of the two risks. So the null hypothesis <span class="math inline">\(H_0:r_1=r_2 \equiv r_1-r_2=0\)</span>, for the risk of CVD among smokers and non-smokers respectively, is expressed as <span class="math inline">\(H_0: RR=\frac{r_1}{r_2}=1\)</span>. Here, <span class="math inline">\(RR\)</span> is the <em>relative risk</em> or the CVD risk <em>ratio</em> between the two exposure groups.</p>
<p>We will reach a conclusion about whether the observed relative risk <span class="math inline">\(RR=2.77&gt;1\)</span>, more than what would be expected by chance, by constructing a 95% confidence interval. If this confidence interval does not contain <span class="math inline">\(RR=1\)</span>, then we will <em>reject</em> <span class="math inline">\(H_0\)</span> in favor of the alternative <span class="math inline">\(RR\neq 1\)</span>. Let’s consult the relevant output in the <span class="math inline">\(2\times 2\)</span> contingency table above (see Table 2). The output generating the point estimate and 95% confidence interval of the relative risk of CVD between smokers and non-smokers in the EGAT study is as follows:</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-rr" class="anchored">

<div class="tabwid">
<style>.cl-26c1b49e{table-layout:auto;}.cl-26b922de{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-26bcab66{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-26bcab70{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-26bcbeb2{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26bcbeb3{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26bcbeb4{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26bcbebc{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table class="cl-26c1b49e">
<caption>Table&nbsp;8.4:  Estimation of the relative CVD risk between smokers and non-smokers in the EGAT study. </caption>
<thead>
<tr style="overflow-wrap:break-word;">
<th colspan="2" class="cl-26bcbeb2"><p class="cl-26bcab66"><span class="cl-26b922de"></span></p></th>
<th colspan="2" class="cl-26bcbeb3"><p class="cl-26bcab70"><span class="cl-26b922de">95% confidence interval</span></p></th>
</tr>
<tr style="overflow-wrap:break-word;">
<th class="cl-26bcbeb2"><p class="cl-26bcab66"><span class="cl-26b922de"></span></p></th>
<th class="cl-26bcbeb3"><p class="cl-26bcab70"><span class="cl-26b922de">Point estimate</span></p></th>
<th class="cl-26bcbeb3"><p class="cl-26bcab70"><span class="cl-26b922de">Lower bound</span></p></th>
<th class="cl-26bcbeb3"><p class="cl-26bcab70"><span class="cl-26b922de">Upper bound</span></p></th>
</tr>
</thead>
<tbody><tr style="overflow-wrap:break-word;">
<td class="cl-26bcbeb4"><p class="cl-26bcab66"><span class="cl-26b922de">Relative risk</span></p></td>
<td class="cl-26bcbebc"><p class="cl-26bcab70"><span class="cl-26b922de">2.768196</span></p></td>
<td class="cl-26bcbebc"><p class="cl-26bcab70"><span class="cl-26b922de">1.500194</span></p></td>
<td class="cl-26bcbebc"><p class="cl-26bcab70"><span class="cl-26b922de">5.107944</span></p></td>
</tr></tbody>
</table>
</div>
</div>
</div>
</div>
<p>Since the 95% confidence interval <span class="math inline">\((1.5, 5.11)\)</span> does not include the value <span class="math inline">\(RR=1\)</span>, which is explicitly anticipated by the null hypothesis of no difference in CVD risk, we reject <span class="math inline">\(H_0:RR=1\)</span>. The conclusion is that the risk of CVD is <em>different</em> between smokers and non-smokers. A straightforward inspection of the point estimate <span class="math inline">\(RR=2.77\)</span>, suggests that the risk of CVD is significantly elevated among smokers compared to non-smokers.</p>
</section></section><section id="the-odds-and-odds-ratio" class="level2" data-number="8.6"><h2 data-number="8.6" class="anchored" data-anchor-id="the-odds-and-odds-ratio">
<span class="header-section-number">8.6</span> The odds and odds ratio</h2>
<p>Another way to go about understanding differences in risk is using the odds ratio. Before we get to that, let’s define the concept of <em>odds</em>. Odds is the ratio between the proportion of those who experienced an event over the proportion of those who did not among the exposed and similarly among the unexposed. In the EGAT study (Table 2), the odds of CVD among smokers is <span class="math display">\[odds_1=\frac{\frac{31}{1417}}{\frac{1386}{1417}}=\frac{31}{1386}=0.0224\]</span></p>
<p>Similarly, the odds of CVD among non-smokers is <span class="math display">\[odds_2=\frac{\frac{15}{1898}}{\frac{1883}{1898}}=\frac{15}{1883}=0.00797\]</span></p>
<p>Similarly to the concept of a relative risk, we have the idea of an odds <em>ratio</em>. This is the ratio of the odds among exposed and unexposed individuals, i.e.,</p>
<div class="cell">

</div>
<p><span class="math display">\[OR=\frac{odds_1}{odds_2}=\frac{31\times 1883}{15\times 1386}=2.81\]</span></p>
<p>Going back to Table 2 we see that we can estimate the odds ratio as the ratio of the product of the counts in the main diagonal of the table (cells [1,2] and [2,3]) divided by the product of the counts on the secondary diagonal (cells [1,3] and [2,2]).</p>
<section id="case-control-studies" class="level3"><h3 class="anchored" data-anchor-id="case-control-studies">Case-control studies</h3>
<p>From these calculations we understand that the odds is not a measure of risk. It’s simply a measure of the increase or decrease of the proportion of some characteristic of interest (e.g., a disease, response to therapy, etc.) between two groups. So, it would not be unreasonable to ask why we need the odds ratio at all, given that we have the relative risk to work with. So what’s the attraction here? Why has the odds ratio, as a measure of the relative risk persisted over time and is used widely to this day? There are three reasons for the persistence of the odds ratio as a measure of risk: case-control studies; case-control studies; case-control studies!</p>
<p>Let’s recall the EGAT study. This study, despite having recruited almost 3,500 people and followed them for twelve years, based its conclusions about whether smoking is associated with increased risk of death from cardiovascular disease on a mere 46 CVD-related deaths! As a result, the lower bound of the 95% confidence interval of the relative risk was barely above 1. The conclusion that smoking is associated with an increased risk of CVD death was statistically significant only because of the dramatic increase in the risk associated with smoking. Any lower value of the risk ratio would have resulted in an unclear result. The same is true in most such studies. The design involves the selection of two or more cohorts of study participants who have some exposure (e.g., receive some medication to prevent the occurrence of an event or are exposed to some risk factor). As in the EGAT study, we then enroll these subjects in the study and then … we wait; and wait; and wait for the event of interest to occur in a sufficient number of study participants so that we can compare the two groups and extract a conclusion about whether taking a medication or being exposed to some risk factor alters the likelihood of experiencing the event of interest.</p>
<p>Alternatively, we can go on some hospital database and select the number of <em>events</em> we are interested in (“cases”) and then select in some manner individuals who did not experience the event of interest (“controls”) who are otherwise as similar to the cases as possible. For example, consider the following <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3046902/">study</a> (Newton-Bishop et al., <em>Eur J Cancer</em> 2011), which explores the possible association of sun exposure with melanoma. There, 960 cases (people who had melanoma) were identified in Yorkshire and the Nothern Region of the river Tyne in the UK) and were matched to 513 individuals from the surrounding population who did not have melanoma. The <span class="math inline">\(2\times 2\)</span> table summarizing previous sun exposure (expressed as having experienced at least one sunburn after the age of 20) was available on 1,335 of the 1,473 individuals who participated in the study and is shown below (bottom of Table 2 in paper describing the melanoma study):</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-example1" class="anchored">

<div class="tabwid">
<style>.cl-26ebeeda{table-layout:auto;}.cl-26e410de{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-26e7150e{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-26e71518{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-26e72742{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26e72743{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26e7274c{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26e7274d{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26e72756{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-26e72757{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style>
<table class="cl-26ebeeda">
<caption>Table&nbsp;8.5:  Occurrence of melanoma by sun exposure. </caption>
<thead>
<tr style="overflow-wrap:break-word;">
<th class="cl-26e72742"><p class="cl-26e7150e"><span class="cl-26e410de"></span></p></th>
<th colspan="2" class="cl-26e72743"><p class="cl-26e71518"><span class="cl-26e410de">Sun burn after 20?</span></p></th>
<th class="cl-26e72743"><p class="cl-26e71518"><span class="cl-26e410de"></span></p></th>
</tr>
<tr style="overflow-wrap:break-word;">
<th class="cl-26e72742"><p class="cl-26e7150e"><span class="cl-26e410de">Melanoma?</span></p></th>
<th class="cl-26e72743"><p class="cl-26e71518"><span class="cl-26e410de">Yes </span></p></th>
<th class="cl-26e72743"><p class="cl-26e71518"><span class="cl-26e410de">No</span></p></th>
<th class="cl-26e72743"><p class="cl-26e71518"><span class="cl-26e410de">Total</span></p></th>
</tr>
</thead>
<tbody>
<tr style="overflow-wrap:break-word;">
<td class="cl-26e7274c"><p class="cl-26e7150e"><span class="cl-26e410de">Yes</span></p></td>
<td class="cl-26e7274d"><p class="cl-26e71518"><span class="cl-26e410de">297</span></p></td>
<td class="cl-26e7274d"><p class="cl-26e71518"><span class="cl-26e410de">561</span></p></td>
<td class="cl-26e7274d"><p class="cl-26e71518"><span class="cl-26e410de">858</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-26e7274c"><p class="cl-26e7150e"><span class="cl-26e410de">No</span></p></td>
<td class="cl-26e7274d"><p class="cl-26e71518"><span class="cl-26e410de">130</span></p></td>
<td class="cl-26e7274d"><p class="cl-26e71518"><span class="cl-26e410de">347</span></p></td>
<td class="cl-26e7274d"><p class="cl-26e71518"><span class="cl-26e410de">477</span></p></td>
</tr>
<tr style="overflow-wrap:break-word;">
<td class="cl-26e72756"><p class="cl-26e7150e"><span class="cl-26e410de">Total</span></p></td>
<td class="cl-26e72757"><p class="cl-26e71518"><span class="cl-26e410de">427</span></p></td>
<td class="cl-26e72757"><p class="cl-26e71518"><span class="cl-26e410de">908</span></p></td>
<td class="cl-26e72757"><p class="cl-26e71518"><span class="cl-26e410de">1,335</span></p></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>From this table, we can calculate the relative risk as <span class="math inline">\(RR=1.13\)</span> with an associated 95% confidence interval <span class="math inline">\((1.04, 1.22)\)</span> and go on to conclude that there is some weak evidence of a statistically significant elevation of melanoma risk among those who had experienced a sunburn after their 20th year. But something is wrong.</p>
<p>If these data are to be believed, there is a devastating epidemic of melanoma in Yorkshire! After all, (858/1335) x 100= <span class="math inline">\(64.3\%\)</span> of the study population had experienced melanoma. Is it sun spots? Is it the famous English fair complexion in combination with summer vacations in sunnier environs? What is going on? What is happening is that we are in effect analyzing a <em>retrospective</em> study as if it were a prospective study. A retrospective study is one where the event has already occurred, and we look back for the reasons. A prospective study by contrast is one where we don’t know whether the event has happened at the start of the study and we look forward in time to see if it occurs. In the melanoma study, researchers identified almost 900 melanoma cases, but these cases did not occur among the <span class="math inline">\(1335\)</span> subjects participating in the study. The denominator of these melanoma cases could be hundreds of thousands or even millions of people. There were 14.9 million people living in Northern England as of the <a href="https://en.wikipedia.org/wiki/2011_United_Kingdom_census">2011 census</a>, the same period when this study took place. Consequently, the estimation of the relative risk is not accurate. By contrast, the odds ratio is <span class="math inline">\(OR=1.41\)</span>. This number is calculated as a function of proportions within the cases and the controls. So it is valid, despite the retrospective nature of the study design (because we don’t need to know the size of the population that our cases and controls came from as these numbers cancel in the calculation of the odds ratio). And this is why the odds ratio is so popular: it does not care whether the study is prospective or retrospective.</p>
<p>However, can the odds ratio be interpreted as a relative risk? To answer that, let’s return to the EGAT study. This is a prospectively designed study from the perspective that we did not know at the start who would die from CVD. In that study, the relative risk was <span class="math inline">\(RR=2.77\)</span>. The odds ratio was <span class="math inline">\(OR=2.81\)</span>, which is very close to the relative risk. How come? This is the case because death from CVD is a fairly rare event. So the odds ratio <span class="math display">\[
OR=\frac{\frac{31}{1417}\times
           \frac{1883}{1898}}
          {\frac{1386}{1417}\times
           \frac{15}{1898}} \approx
      \frac{\frac{31}{1417}}
           {\frac{15}{1898}}=
           2.77=RR\]</span> The above approximation is possible because the proportions of those who did not experience CVD are almost 100% (i.e., <span class="math inline">\(\frac{1883}{1898}\approx 1\)</span> and <span class="math inline">\(\frac{1386}{1417} \approx 1\)</span>). So, for rare events, <span class="math inline">\(OR \approx RR\)</span> and the odds ratio can be interpreted as a relative risk!</p>
<p>Given that melanoma is fairly rare cancer, the odds ratio in the melanoma study will be close to the true relative risk in the population; a lot closer than the relative risk produced by the case-control study. So our point estimate of the odds ratio <span class="math inline">\(OR=1.41\)</span>, suggests that the elevation of melanoma risk associated with sun exposure is <span class="math inline">\(41.3\%\)</span> and not <span class="math inline">\(12.6\%\)</span> as would be suggested by the relative risk estimate.</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./more_samples.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Inference for numerical data: &gt;2 samples</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./correlation.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Copyright 2022, Konstantinos I. Bougioukas</div>   
  </div>
</footer><script>var lightboxQuarto = GLightbox({"openEffect":"zoom","selector":".lightbox","loop":true,"descPosition":"bottom","closeEffect":"zoom"});</script>


</body></html>